# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Argodis UG (haftungsbeschränkt)
tagline:             'Technology Expertise'
description:         'Official company website'
url:                 https://argodis.de
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Venelin Petkov

# Custom vars
version:             1.0.0

# More
plugins: [jekyll-paginate]
paginate-path: "page:num"
